apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: online-shop-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/triotechltd/new-pipeline-test.git
    targetRevision: main
    path: declarative_approach/online-shop

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
